DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS authors;

CREATE TABLE books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL


);
-- CREATE TABLE weather (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--      bio TEXT NOT NULL,
--      author_id  BIGINT REFERENCES flowers(id)
-- );
CREATE TABLE authors (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    bio TEXT NOT NULL,
    author_id  TEXT NOT NULL
);